### ISSUE TITLE
undefined "stock" in alpha version

### ISSUE THREAD

**Issue by Ephigenia** [Ephigenia/ikea-availability-checker#107]
Original report from @[okniazik](https://github.com/okniazik) in https://github.com/Ephigenia/ikea-availability-checker/issues/100#issuecomment-1105147414

```
npx ikea-availability-checker@2.0.0-alpha.1 stock --country pl 80382321                          
Need to install the following packages:
  ikea-availability-checker@2.0.0-alpha.1
Ok to proceed? (y) y
/Users/ephigenia/.npm/_npx/dc2879d1cfed7f18/node_modules/ikea-availability-checker/source/cli-stock.js:152
      .then(results => results.filter(item => item.availability.stock >= opts.minStock))
                                                                ^

TypeError: Cannot read properties of undefined (reading 'stock')
    at /Users/ephigenia/.npm/_npx/dc2879d1cfed7f18/node_modules/ikea-availability-checker/source/cli-stock.js:152:65
    at Array.filter (<anonymous>)
    at /Users/ephigenia/.npm/_npx/dc2879d1cfed7f18/node_modules/ikea-availability-checker/source/cli-stock.js:152:32
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

- OS: OSX
- Version 2.0.0-alpha.1

**Comment by Ephigenia** [comment]
Issue fixed in new alpha release … 

```
npx ikea-availability-checker@2.0.0-alpha.2 stock --country pl 80382321
```
