### ISSUE TITLE
SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by nicoske** [Ephigenia/ikea-availability-checker#92]
**Describe the bug**
Cannot check stock - SyntaxError

**To Reproduce**
```
$ ikea-availability stock --country be 30346934
/usr/local/lib/node_modules/ikea-availability-checker/source/lib/iows2.js:232
        if (err.request?.res) {
                        ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/ikea-availability-checker/source/cli-stock.js:8:13)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

```

**Client (please complete the following information):**
Debian Bullseye
NodeJS v12.22.5
Installed from npm

**Comment by nicoske** [comment]
My bad.. Didn't noticed the required node version

**Comment by Ephigenia** [comment]
@nicoske which node version where you using?

**Comment by nicoske** [comment]
@Ephigenia 12.22.5 which is shipped with Debian 11
